fuel_cost_2011 <- readr::read_csv("data-raw/fuel-cost-2011.csv")
fuel_cons_param <- readr::read_csv("data-raw/webTagA138.csv")
fuel_split <- readr::read_csv("data-raw/fuel-split.csv")
pag_t532 <- readr::read_csv("data-raw/pagT532.csv")
non_fuel_param <- readr::read_csv("data-raw/non-fuel-param.csv")
purpose_splits <- readr::read_csv("data-raw/purpose-splits.csv")
occ_splits <- readr::read_csv("data-raw/occ-splits.csv")
w_ave_vot <- readr::read_csv("data-raw/w-ave-vot.csv")

devtools::use_data(fuel_cost_2011)
devtools::use_data(fuel_cons_param)
devtools::use_data(fuel_split)
devtools::use_data(pag_t532)
devtools::use_data(non_fuel_param)
devtools::use_data(purpose_splits)
devtools::use_data(occ_splits)
devtools::use_data(w_ave_vot)
