#' A Function to convert the base cost breakdown into Total Scheme Budget (TSB) and Target Costs(TC) in base year factor prices
#'
#' This function generates TSB and TC in base year factor prices
#' @param baseCosts The output dataframe generated by the costBreakdown() function
#' @param cpiBase The consumer price index in the appraisal base year (2011). Defaults to 103.8 (see CSO, indexed to Dec. 2006)
#' @param cpiCostEst The consumer price index in the month & year of the cost estimate (see CSO, indexed to Dec. 2006)
#' @param risk A percentage allowance for programme risk, entered as a decimal. Defaults to 0.05 / 5%
#' @param sppf The shadow price of public funds. Defaults to 1.3
#' @param spl The shadow price of labour. Defaults to 0.8
#' @keywords cba, costs
#' @return A dataframe of Total Scheme Budget (TSB) and Target Costs (TC) in base year factor prices
#' @export

baseCostFact <- function(baseCosts, cpiBase = 103.8, cpiCostEst, risk = 0.05, sppf = 1.3, spl = 0.8) {
    
    uninflTC <- sum(baseCosts$value) * (cpiBase / cpiCostEst)
    uninflTSB <- (sum(baseCosts$value) * (cpiBase / cpiCostEst)) * (1 + risk)
    
    
    baseCostFact <- data_frame(expenditure = c("construction", "supervision", "archaeology", "advanceWorks", "residualNetwork", 
                                               "landProperty", "planningDesign")) %>%
        mutate(totalSchemeBudget = baseCosts$value * (uninflTSB / sum(baseCosts$value)) * 
                   (1 / (1 + baseCosts$vatRate)) * 
                   ((baseCosts$govFunds * sppf) + (1 - baseCosts$govFunds)) *
                   ((baseCosts$labourContent * spl) + (1 - baseCosts$labourContent))) %>% 
        mutate(targetCost = baseCosts$value * (uninflTC / sum(baseCosts$value)) * 
                   (1 / (1 + baseCosts$vatRate)) * 
                   ((baseCosts$govFunds * sppf) + (1 - baseCosts$govFunds)) *
                   ((baseCosts$labourContent * spl) + (1 - baseCosts$labourContent)))
}